export const fontFamilies = {
  heading: "var(--font-playfair), 'Playfair Display', Georgia, serif",
  body: "var(--font-jost), 'Jost', system-ui, sans-serif",
  signature: "var(--font-cormorant), 'Cormorant Garamond', Georgia, serif",
} as const;

/** Shared responsive sizes — phone → tablet → desktop */
export const typeScale = {
  hero: { base: "1.875rem", sm: "2.375rem", md: "3.25rem", lg: "3.75rem" },
  pageTitle: { base: "1.625rem", sm: "1.875rem", md: "2.25rem", lg: "2.5rem" },
  section: { base: "1.375rem", sm: "1.5rem", md: "1.75rem", lg: "1.875rem" },
  card: { base: "0.9375rem", md: "1.0625rem" },
  body: { base: "0.9375rem", md: "1rem" },
  bodyLg: { base: "1rem", md: "1.125rem" },
  italic: { base: "1.0625rem", sm: "1.25rem", md: "1.5rem" },
  italicLg: { base: "1.25rem", md: "1.5rem", lg: "1.625rem" },
  caption: { base: "0.75rem", md: "0.8125rem" },
  label: { base: "0.625rem", md: "0.6875rem" },
  button: { base: "0.625rem", md: "0.6875rem" },
  buttonLg: { base: "0.6875rem", md: "0.75rem" },
} as const;

export const textStyles = {
  display: {
    fontFamily: fontFamilies.heading,
    fontWeight: 500,
    letterSpacing: "0.02em",
    lineHeight: 1.15,
    color: "oiva.cocoa",
  },
  displayLarge: {
    fontFamily: fontFamilies.heading,
    fontSize: typeScale.hero,
    fontWeight: 500,
    letterSpacing: { base: "0.02em", md: "0.04em" },
    lineHeight: 1.15,
    color: "oiva.cocoa",
  },
  subhead: {
    fontFamily: fontFamilies.heading,
    fontSize: typeScale.section,
    fontWeight: 500,
    letterSpacing: "0.02em",
    lineHeight: 1.3,
    color: "oiva.cocoa",
  },
  pageTitle: {
    fontFamily: fontFamilies.heading,
    fontSize: typeScale.pageTitle,
    fontWeight: 500,
    letterSpacing: { base: "0.02em", md: "0.04em" },
    lineHeight: 1.2,
    color: "oiva.cocoa",
  },
  signature: {
    fontFamily: fontFamilies.signature,
    fontStyle: "italic",
    fontWeight: 400,
    fontSize: typeScale.italic,
    color: "oiva.cocoa",
  },
  signatureLarge: {
    fontFamily: fontFamilies.signature,
    fontStyle: "italic",
    fontSize: typeScale.italicLg,
    fontWeight: 400,
    lineHeight: 1.35,
    color: "oiva.cocoa",
  },
  body: {
    fontFamily: fontFamilies.body,
    fontSize: typeScale.body,
    fontWeight: 300,
    lineHeight: { base: 1.7, md: 1.75 },
    color: "oiva.ink",
  },
  label: {
    fontFamily: fontFamilies.body,
    fontSize: typeScale.label,
    fontWeight: 500,
    letterSpacing: { base: "0.16em", md: "0.2em" },
    textTransform: "uppercase" as const,
    color: "oiva.cocoa",
  },
  caption: {
    fontFamily: fontFamilies.body,
    fontSize: typeScale.caption,
    fontWeight: 300,
    lineHeight: 1.5,
    color: "oiva.taupe",
  },
  navLink: {
    fontFamily: fontFamilies.body,
    fontSize: typeScale.label,
    fontWeight: 500,
    letterSpacing: { base: "0.12em", md: "0.15em" },
    textTransform: "uppercase" as const,
    color: "oiva.cocoa",
  },
} as const;
